# Generated by Django 3.2.10 on 2023-11-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
