# Generated by Django 3.2.10 on 2023-12-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_followers_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers_count',
        ),
    ]
