services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn Django_SocialMediaApp.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: https://django-socialmediaapp.onrender.com
      # Add other necessary environment variables here
