# Generated by Django 3.2.10 on 2023-11-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
